### ISSUE TITLE
bos-brower 文件上传状态一直显示 ”待上传“

### ISSUE THREAD

**Issue by WM-bos** [baidubce/bce-client#14]

**Comment by sqzhou** [comment]
用的是那个哪个版本，怎样操作的，方便描述吗？最好说明下上传多少文件，文件大小之类的，我们这边好复现修改下。 @WM-bos

**Comment by sqzhou** [comment]
另外，通过退出登录，重新登录的方式，能还是待上传吗？ @WM-bos

**Comment by WM-bos** [comment]
您好，

问题已经解决了 感谢！


Best regards,
Bonnie


From: sqzhou ***@***.***>
Reply-To: baidubce/bce-client ***@***.***>
Date: Monday, July 15, 2024 at 20:08
To: baidubce/bce-client ***@***.***>
Cc: v_wangmiao04 ***@***.***>, Mention ***@***.***>
Subject: Re: [baidubce/bce-client] bos-brower 文件上传状态一直显示 ”待上传“ (Issue #14)


另外，通过退出登录，重新登录的方式，能还是待上传吗？ @WM-bos<https://mailshield.baidu.com/check?q=G74am%2fVNhDyhOhJuBSLSckPPn%2br0AkneKVgSPDoFsB4%3d>
